version: "3.8"

services:
  # Django application
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Expose Django app port
    volumes:
      - .:/app  
    environment:
      MONGO_HOST: weather_vincenzo
      MONGO_PORT: 27017

  mongo:
    image: mongo
